name: Core Checks

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'release-*'
  pull_request:
    branches:
      - '*'

jobs:
  check-vscode-npm-versions-match:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check npm Visual Studio Code Versions
        shell: pwsh
        run: |
          ./.github/ci/scripts/Confirm-NpmVisualStudioCodeVersionsMatch.ps1 -NpmPackageJsonPath ../package.json -NpmPackageLockJsonPath ../package-lock.json
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm run install-dependencies
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
